#!/bin/bash

export COLOR_NC='\e[0m' # No Color
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[0;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'

export nc=$'\e[0m'
export gry=$'\e0;30'
export red=$'\e[0;31m'
export grn=$'\e[0;32m'
export blu=$'\e[0;34m'
export mag=$'\e[0;35m'
export cyn=$'\e[1;36m'
export light_cyn=$'\e[0;36m'
export white=$'\e[1;37m'
export ylw=$'\e[0;33m'

grep_opts='--color=auto'      # for aliases since $GREP_OPTIONS is deprecated
grep_color=$COLOR_LIGHT_GREEN             # (legacy) bright green rather than default red
grep_colors="ms=$grep_color"  # (new) Matching text in Selected line = green
