#!/bin/bash

if type nvim >/dev/null 2>/dev/null; then
  vim --version | head -n 1
else
  alias vim=nvim
  nvim --version | head -n 1
fi

# Source from script to regenerate .gen
alias srcbash="source $REPO/scripts/setup.sh"

# Basics
alias als="vim ~/.gen"
alias afind='ack -il'
alias history='fc -l 1'
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias lsa='ls -lah'
alias md='mkdir -p'
alias sudo='sudo '
alias po='popd'
alias pu='pushd'
alias rd='rmdir'
alias cp='cp -i'
alias mv='mv -i'

# logkeys
alias export-keymap='sudo logkeys --export-keymap en_US.keymap'
alias logkeys-start='sudo logkeys --start --keymap ~/i18n/en_US.keymap'
alias logkeys-stop='sudo logkeys --k'
alias fllk='sudo tail --follow /var/log/logkeys.log'

# Search
alias grep='grep $grep_opts'
alias egrep='egrep $grep_opts'
alias fgrep='fgrep $grep_opts'

# Bash
alias bp='vim ~/.bash_profile'
alias srcbp='source ~/.bash_profile'
alias bsh='vim ~/.bashrc'
alias srcbsh='source ~/.bashrc'
alias pf='vim ~/.profile'
alias srcpf='source ~/.profile'

# Directories
alias ~='cd ~'                                  # ~:            Go Home
alias path='echo -e ${PATH//:/\\n}'             # path:         Echo all executable Paths
alias dotfiles='cd ~/.dotfiles'                 # dotfiles:     Go to custom dotfiles directory

# Utilities
alias fixtty='reset; stty sane; tput rs1; clear; echo -e "\033c"'
alias DT='tee ~/Desktop/terminalOut.txt'
