#!/bin/bash/
#  ---------------------------------------------------------------------------
#  Description:  This file holds human readible networking utils.
#  Motivation:   Shortcut cmds <ifconfig> | ps aux | ipconfig | ipfw
#  ---------------------------------------------------------------------------
#alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
#alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
#alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
#alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
#alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
#alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IP

#   ii:  display useful host related informaton
#   -------------------------------------------------------------------
function ii() {
  echo -e "\n${ylw}Logged on as: ${nc}$USER"
  echo -e "${ylw}Hostname: ${nc}$HOSTNAME"
  echo -e "\n${grn}Current date: ${nc}"; date
  echo -e "\n${grn}System information: ${nc}"; sys_info
  echo -e "\n${grn}Machine stats: ${nc}"; uptime
  echo -e "\n${grn}LAN: ${white} " ; iip
  echo -e "\n${nc}"
}

#   ip:  display IPv4 and IPv6 public addresses
#   -------------------------------------------------------------------

function iip() {
  echo -e "${gry}$(ifconfig | grep -e ^en*0* -e inet)"
}

function sys_info() {
  os=`uname -s`
  os_r=`uname -r`
  os_v=`uname -v`
  p_arch=`uname -p`

  echo -e "${nc} ${os} ${os_r} ${os_v} ${p_arch}"
}

# edit_hosts: Edit /etc/hosts file
alias edit_hosts='sudo edit /etc/hosts'
alias sshd-logs='sudo tail -f /var/log/auth.log'

# find_pid: Find out the pid of a specified process
# -----------------------------------------------------
# Note that the command name can be specified via a regex
# E.g. findPid '/d$/' finds pids of all processes with names ending in 'd'
# Without the 'sudo' it will only find processes of the current user
#   -----------------------------------------------------
function find-pid() { lsof -t -c "$@" ; }

# http_headers:      Grabs headers from web page
function http-headers() { /usr/bin/curl -I -L $@ ; }
