#!/bin/bash
dir="$( dirname "$0" )"
cd "$dir/.."
ruby="$(which ruby || rbenv which ruby)"

# Install Homebrew if not installed
function install_brew() {
  $(which -s brew)
  if [[ $? == 0 ]] ; then
    while true; do
      echo "Some packages in this repository are installed using Homebrew."
      read -p "Do you wish to install this now? (y/Y)es/(n/N)o `echo $'\n> '`" yn
      case $yn in
        [Yy]* ) $ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; break;;
        [Nn]* ) exit;;
        * ) echo $'\n> ';;
      esac
    done
  else
    echo "Updating Homebrew.."
    brew update
  fi
}

# Runs brew installation for first script execution
if [ -d "$dir/history" ];
then :; else install_brew
fi
