#!/bin/bash
# NOTE: .bash_profile is only sourced in login shells (SSH, etc)
# Set environment variables and startup programs here.

echo "$(bash --version | head -2)"
shopt -q login_shell && echo -e "\nSourced .bash_profile" || echo -e "\nSourced .profile"

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
export PATH="$PATH:/opt/yarn-[version]/bin"

# export ZEPHYR_TOOLCHAIN_VARIANT="gnuarmemb"
export GNUARMEMB_TOOLCHAIN_PATH="/home/tlcie/gcc-arm-none-eabi-10-2020-q4-major"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"
export SSHAGENT=/usr/bin/ssh-agent
export SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT"  ]; then
  eval `$SSHAGENT $SSHAGENTARGS`
  trap "kill $SSH_AGENT_PID" 0
fi
