#!/bin/bash

# Shell safeguard for non-interactive .bashrc circumstances
# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return;;
esac

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILESIZE=2000
HISTSIZE=1000000
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
HISTFILE=~/.bash_history_actual

# append to the history file, don't overwrite it
shopt -s histappend
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# NOTE .bashrc is intended for use in interactive, non-login shells.
# Custom aliases, functions, and shell configurations sourced here.
# ------------------------------------------------------------------
[[ -f ~/.sources ]] && source ~/.sources
force_color_prompt=yes
if [[ $TERM =~ .*"-256color".* ]]; then :
else
  export TERM=$TERM-256color
fi
# make less more friendly for non-text input files, see lesspipe(1)
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
# [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


export PATH="$PATH:/usr/local/bin/"
export PATH="$PATH:$HOME/.npm-packages/bin"
[ -f ~/.go ] && source ~/.go
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export PATH=/home/laujonat/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#export DOCKER_HOST=tcp://localhost:2375

# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/__tabtab.bash ] && . ~/.config/tabtab/__tabtab.bash || true
export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
export ZEPHYR_SDK_INSTALL_DIR=/home/laujonat/.local/zephyr-sdk-0.11.2


export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
PATH=$PATH:$GOPATH/bin # Add GOPATH/bin to PATH for scripting
