#!/bin/bash

#export REPO=$( cd '$( dirname "${BASH_SOURCE[0]})'  >/dev/null 2>&1 && pwd )
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1

# set SSH_AUTH_SOCK env var to a fixed value
export SSH_AUTH_SOCK=~/.ssh/ssh-agent.sock

# test whether $SSH_AUTH_SOCK is valid
ssh-add -l 2>/dev/null >/dev/null
# if not valid, then start ssh-agent using $SSH_AUTH_SOCK
[ $? -ge 2 ] && ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null

if [ -d "$HOME/bin" ] ; then
  PATH="$PATH:$HOME/bin"
fi

PATH="$HOME/.npm-global/bin:$PATH"


# GOPATH="$HOME/.go"
# export GOPATH
# PATH=$PATH:$GOPATH/bin # Add GOPATH/bin to PATH for scripting

PATH="$PATH:/mnt/c/Users/telne/AppData/Local/Programs/Microsoft VS Code"

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
